package br.ufscar.pescd.entity.enums;

public enum StatusAluno {
    NAO_ENVIADO,
    PLANO_ENVIADO,
    PLANO_APROVADO,
    DOCUMENTACAO_ENVIADA,
    RELATORIO_ENVIADO,
    RELATORIO_APROVADO_SUPERVISOR,
    CONCLUIDO_PELO_RESPONSAVEL
}
